<a href="https://colab.research.google.com/github/has9800/pytorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


In [2]:
!nvidia-smi

Thu Feb 13 06:02:13 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
if torch.cuda.is_available():
  print("GPU is available:", torch.cuda.get_device_name(0))
else:
  print("GPU is not available.")

GPU is available: Tesla T4


Tensors

In [4]:
# scalar
scalar = torch.tensor(3)

scalar

tensor(3)

In [5]:
# find the dimensions using ndim
scalar.ndim

0

In [6]:
# vector
vector = torch.tensor([2, 4])

vector

tensor([2, 4])

In [7]:
vector.ndim

1

In [8]:
# matrix
matrix = torch.tensor([[2, 4], [6, 8]])

matrix

tensor([[2, 4],
        [6, 8]])

In [9]:
matrix.ndim

2

In [10]:
# tensor
tensor = torch.tensor([[[2, 4], [6, 8], [10, 12], [1, 2], [3, 4], [5, 6]]])

tensor

tensor([[[ 2,  4],
         [ 6,  8],
         [10, 12],
         [ 1,  2],
         [ 3,  4],
         [ 5,  6]]])

In [11]:
tensor.ndim

3

In [12]:
# random tensors - pytorch creates random tensors under the hood for ml learning
random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.9758, 0.4933, 0.6485, 0.2948],
        [0.2550, 0.6475, 0.9920, 0.0986],
        [0.4436, 0.0050, 0.3832, 0.3647]])

In [13]:
random_tensor.ndim

2

In [14]:
# tensors as images
image_tensor = torch.rand(size=(224, 224, 3))

image_tensor.shape, image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
image_tensor

tensor([[[0.2010, 0.4448, 0.0818],
         [0.5504, 0.4629, 0.3304],
         [0.1561, 0.4341, 0.9005],
         ...,
         [0.0834, 0.1819, 0.3935],
         [0.3572, 0.3268, 0.4363],
         [0.2443, 0.1047, 0.3512]],

        [[0.6489, 0.9148, 0.4308],
         [0.6397, 0.8854, 0.9286],
         [0.8141, 0.8217, 0.9414],
         ...,
         [0.7182, 0.6127, 0.7370],
         [0.6735, 0.3460, 0.8046],
         [0.0025, 0.5910, 0.7264]],

        [[0.3898, 0.7242, 0.1524],
         [0.8666, 0.9794, 0.6044],
         [0.2265, 0.9245, 0.0030],
         ...,
         [0.6222, 0.8509, 0.9855],
         [0.3478, 0.6197, 0.9586],
         [0.4080, 0.8147, 0.1936]],

        ...,

        [[0.5785, 0.1453, 0.5429],
         [0.6170, 0.4639, 0.5370],
         [0.1027, 0.1190, 0.3912],
         ...,
         [0.3174, 0.3131, 0.9569],
         [0.6971, 0.0490, 0.0588],
         [0.5063, 0.2674, 0.8485]],

        [[0.1964, 0.3180, 0.7504],
         [0.2186, 0.5870, 0.3551],
         [0.

In [16]:
# tensors of ones and zeros - zeros used for masking
zeros = torch.zeros(size=(3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# tensor range
one_to_ten = torch.arange(start=2, end=13, step=2)

one_to_ten

tensor([ 2,  4,  6,  8, 10, 12])

In [18]:
# assign a dtype - grad is if you want pytorch to track gradients when calculating
float_tensor = torch.tensor([[3, 4], [5, 6]], dtype=torch.int32, device="cuda", requires_grad=False)

float_tensor.dtype

torch.int32

In [19]:
# change the dtype
float_tensor = float_tensor.type(torch.float16)

float_tensor.dtype

torch.float16