<a href="https://colab.research.google.com/github/has9800/pytorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch

In [19]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


In [20]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [21]:
if torch.cuda.is_available():
  print("GPU is available:", torch.cuda.get_device_name(0))
else:
  print("GPU is not available.")

GPU is not available.


Tensors

In [22]:
# scalar
scalar = torch.tensor(3)

scalar

tensor(3)

In [23]:
# find the dimensions using ndim
scalar.ndim

0

In [24]:
# vector
vector = torch.tensor([2, 4])

vector

tensor([2, 4])

In [25]:
vector.ndim

1

In [26]:
# matrix
matrix = torch.tensor([[2, 4], [6, 8]])

matrix

tensor([[2, 4],
        [6, 8]])

In [27]:
matrix.ndim

2

In [28]:
# tensor
tensor = torch.tensor([[[2, 4], [6, 8], [10, 12], [1, 2], [3, 4], [5, 6]]])

tensor

tensor([[[ 2,  4],
         [ 6,  8],
         [10, 12],
         [ 1,  2],
         [ 3,  4],
         [ 5,  6]]])

In [29]:
tensor.ndim

3

In [32]:
# random tensors - pytorch creates random tensors under the hood for ml learning
random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.6786, 0.1441, 0.7540, 0.8663],
        [0.6921, 0.1813, 0.1653, 0.5099],
        [0.2606, 0.9813, 0.7023, 0.4304]])

In [33]:
random_tensor.ndim

2

In [39]:
# tensors as images
image_tensor = torch.rand(size=(224, 224, 3))

image_tensor.shape, image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [40]:
image_tensor

tensor([[[0.8650, 0.9645, 0.4398],
         [0.6175, 0.7079, 0.2247],
         [0.4507, 0.1192, 0.9151],
         ...,
         [0.4629, 0.8665, 0.1529],
         [0.6337, 0.1872, 0.1423],
         [0.9610, 0.2531, 0.6651]],

        [[0.4647, 0.6105, 0.9787],
         [0.1359, 0.3447, 0.2816],
         [0.4439, 0.2356, 0.5058],
         ...,
         [0.3256, 0.5183, 0.8457],
         [0.3628, 0.1075, 0.2398],
         [0.5100, 0.6032, 0.3118]],

        [[0.2564, 0.6106, 0.4997],
         [0.3770, 0.8512, 0.9291],
         [0.6667, 0.6632, 0.9392],
         ...,
         [0.5641, 0.2474, 0.6628],
         [0.7641, 0.8537, 0.4277],
         [0.1974, 0.1363, 0.5732]],

        ...,

        [[0.2066, 0.0088, 0.5650],
         [0.4796, 0.0804, 0.3105],
         [0.8203, 0.7150, 0.6701],
         ...,
         [0.2551, 0.3861, 0.0640],
         [0.4004, 0.4784, 0.2470],
         [0.1792, 0.7738, 0.6613]],

        [[0.3076, 0.0737, 0.8496],
         [0.1233, 0.8074, 0.1264],
         [0.

In [42]:
# tensors of ones and zeros - zeros used for masking
zeros = torch.zeros(size=(3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
# tensor range
one_to_ten = torch.arange(start=2, end=13, step=2)

one_to_ten

tensor([ 2,  4,  6,  8, 10, 12])

In [46]:
# assign a dtype - grad is if you want pytorch to track gradients when calculating
float_tensor = torch.tensor([[3, 4], [5, 6]], dtype=torch.int32, device="cuda", requires_grad=False)

float_tensor.dtype

torch.int32

In [49]:
# change the dtype
float_tensor = float_tensor.type(torch.float16)

float_tensor.dtype

torch.float16